---
title: "Research"
---

<h2 id="books">Books</h2>

* Andy Baker (2022). [*Shaping the Developing World: The South, the West, and the Natural World: Second Edition.*](https://us.sagepub.com/en-us/nam/shaping-the-developing-world/book249551) Washington, D.C.: Congressional Quarterly Press. [[Request a review copy.]](https://us.sagepub.com/en-us/nam/shaping-the-developing-world/book249551) [[First Edition, 2014]](https://www.abebooks.com/first-edition/Shaping-Developing-World-West-South-Natural/30195993048/bd)

* Andy Baker, Barry Ames, and Lucio Renno (2020). [*Persuasive Peers: Social Communication and Voting in Latin America.*](https://press.princeton.edu/books/paperback/9780691205779/persuasive-peers) [Online appendices and replication materials.](https://doi.org/10.7910/DVN/I8VV7Z)

  * Winner of the 2021 APSA Political Networks Section Best Book Award, awarded every other year for the best book published in the past two years.
  
  * Portuguese translation: *Pares Persuasivos: Comunicação social e votação na América Latina* (2023). Brasília: Editora Universidade de Brasília.
  
  * Reviewed in the following:
  
    * *Perspectives on Politics*
    * *Latin American Research Review*
    * *Bulletin of Latin American Research*

* Andy Baker (2009). [*The Market and the Masses in Latin America: Policy Reform and Consumption in Liberalizing Economies.*](https://doi.org/10.1017/CBO9780511576447) (Cambridge Studies in Comparative Politics). New York: Cambridge University Press.
  * Blog post: [Monkey Cage](https://www.washingtonpost.com/news/monkey-cage/wp/2014/06/02/latin-americans-are-embracing-globalization-and-their-former-colonial-masters/?utm_term=.03412b47947a)
  * Reviewed in the following:
    * *Perspectives on Politics*
    * *Comparative Political Studies*
    * *International Journal of Public Opinion Research*
    * *Latin American Research Review*
    * *Latin American Politics and Society*
    * *Bulletin of Latin American Research*
    * *Choice Reviews Online*
    
----

<h2 id="journal_articles">Refereed Journal Articles</h2>

* Andy Baker and David Cupery (2023). [“Animosity, Amnesia, or Admiration? Mass Opinion around the World toward the Former Colonizer.”](https://doi.org/10.1017/S0007123422000710) *British Journal of Political Science.* [Published version.](https://doi.org/10.1017/S0007123422000710) [Online Appendix.](https://static.cambridge.org/content/id/urn:cambridge.org:id:article:S0007123422000710/resource/name/S0007123422000710sup001.pdf) [Replication materials.](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/F8XTVP)

* Andy Baker (2023). [“The Microfoundations of Latin America’s Social Policy Coalitions: The Insider/Outsider Labor Divide and Attitudes toward Different Welfare Programs in Mexico.”](https://muse.jhu.edu/pub/1/article/875316) *World Politics* 75(1): 99-144. [Online Appendix.](https://muse.jhu.edu/article/875316/file/supp01.pdf) [Replication materials.](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YXBXBB)

* Andy Baker and Dalton Dorr (2022). [“Labor Informality and the Vote in Latin America: A Meta-Analysis.”](https://doi.org/10.1017/lap.2022.4) *Latin American Politics and Society* 64(2): 21-44. [Published version.](https://doi.org/10.1017/lap.2022.4) [Online Appendix.](https://static.cambridge.org/content/id/urn:cambridge.org:id:article:S1531426X22000048/resource/name/S1531426X22000048sup001.pdf) [Replication materials.](https://doi.org/10.7910/DVN/Z5YJ19)

* Andy Baker and Lucio Renno (2019). [“Nonpartisans as False Negatives: The Mismeasurement of Party Identification in Public Opinion Surveys.”](https://www.journals.uchicago.edu/doi/full/10.1086/703129) *Journal of Politics* 81(3): 906-922. [Online Appendix.](https://www.journals.uchicago.edu/doi/suppl/10.1086/703129/suppl_file/170738Appendix.pdf) [Replication materials.](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HK213D)

* Andy Baker and Stefan J. Wojcik (2019). [“Does Democratization Lower Consumer Prices? Regime Type, Prices, and the Consumer–Producer Tradeoff.”](https://journals.sagepub.com/doi/full/10.1177/0192512117731264#:~:text=We%20argue%20and%20find%20that,to%20those%20on%20capital%20goods.) *International Political Science Review* 40(2): 145-160. [Published version (gated).](http://journals.sagepub.com/doi/full/10.1177/0192512117731264)

* Andy Baker and Vania Ximena Velasco-Guachalla (2018). [“Is the Informal Sector Politically Different? (Null) Answers from Latin America.”](https://www.sciencedirect.com/science/article/pii/S0305750X17303066) *World Development* 102: 170-182. [Published version (gated).](https://www.sciencedirect.com/science/article/pii/S0305750X17303066?via%3Dihub)

* Andy Baker, Barry Ames, Anand E. Sokhey, and Lucio R. Renno (2016). ["The Dynamics of Partisan Identification when Party Brands Change: The Case of the Workers Party in Brazil."](https://www.journals.uchicago.edu/doi/full/10.1086/683609) *Journal of Politics* 78(1): 197-213. [Online appendix.](https://www.journals.uchicago.edu/doi/suppl/10.1086/683609/suppl_file/150385Appendix.pdf) [Replication materials.](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XSCFX5)

* Andy Baker, James R. Scarritt, and Shaheen Mozaffar (2016). ["Ethnopolitical Demography and Democracy in Sub-Saharan Africa."](http://www.tandfonline.com/doi/full/10.1080/13510347.2015.1038250#abstract) *Democratization* 23(5): 838-861. [Published version (gated).](http://www.tandfonline.com/doi/full/10.1080/13510347.2015.1038250#abstract) [Online appendix.](https://www.tandfonline.com/doi/suppl/10.1080/13510347.2015.1038250?scroll=top)

* Andy Baker (2015). ["Race, Paternalism, and Foreign Aid: Evidence from U.S. Public Opinion."](https://www.google.com/search?q=Race%2C+Paternalism%2C+and+Foreign+Aid%3A+Evidence+from+U.S.+Public+Opinion.&oq=Race%2C+Paternalism%2C+and+Foreign+Aid%3A+Evidence+from+U.S.+Public+Opinion.&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBBzE0NWowajSoAgCwAgA&sourceid=chrome&ie=UTF-8) *American Political Science Review* 109(1): 93-109. [Online appendix.](./APSR Final Online Appendix.docx) [Replication materials.](https://doi.org/10.7910/DVN/0FXKKX)

  * Relevant blog posts: [Monkey Cage](https://www.washingtonpost.com/news/monkey-cage/wp/2015/03/05/media-portrayals-of-africa-promote-paternalism/?utm_term=.c6e78e6ed938) and [USAPP](http://blogs.lse.ac.uk/usappblog/2015/03/13/white-americans-are-supportive-of-redistribution-to-foreigners-of-african-descent-but-for-prejudicial-and-paternalistic-reasons/)

* Joby Schaffer and Andy Baker (2015). ["Clientelism as Persuasion-Buying: Evidence from Latin America."](http://journals.sagepub.com/doi/abs/10.1177/0010414015574881) *Comparative Political Studies* 48(9): 1093-1126. [Published version (gated).](http://journals.sagepub.com/doi/abs/10.1177/0010414015574881) [Online appendix.](https://journals.sagepub.com/doi/suppl/10.1177/0010414015574881/suppl_file/CPS_computer_code_(1).zip) [Replication materials.](./CPS computer code.zip) [Additional materials.](./CPS SI.docx)

  * Winner of the 2017 Mitchell Seligson Prize for the best scholarship using LAPOP’s AmericasBarometer data that was published in the prior two calendar years.

* Anand E. Sokhey, Andy Baker, and Paul Djupe (2015). ["The Dynamics of Socially Supplied Information: Examining Discussion Network Stability over Time."](https://academic.oup.com/ijpor/article/27/4/565/2357405) *International Journal of Public Opinion Research* 27(4): 565-587. [Published version (gated).](https://academic.oup.com/ijpor/article/27/4/565/2357405)

* Andy Baker and David Cupery (2013). ["Anti-Americanism in Latin America: Economic Exchange, Foreign Policy Legacies, and Mass Attitudes toward the Colossus of the North."](https://www.cambridge.org/core/journals/latin-american-research-review/article/antiamericanism-in-latin-america-economic-exchange-foreign-policy-legacies-and-mass-attitudes-toward-the-colossus-of-the-north/68DBAD4DB711CF00E08293065D72BD61) *Latin American Research Review* 48(2): 106-130. [Online appendix.](./Baker and Cupery Supplemental Online.pdf)

  * Mentioned in the following mass media outlets:

    * [*The New York Times*](https://www.nytimes.com/2017/03/30/opinion/the-blind-spots-in-trumps-foreign-policy.html)

    * [*Huffington Post*](https://www.huffingtonpost.com/2013/07/29/latin-america-views-the-u_n_3672000.html?utm_hp_ref=world&ir=World)

    * [*Efecto Naim*](http://www.americasquarterly.org/AQ-efecto-naim-report-on-anti-americanism-latin-america) [[TV appearance]](http://www.americasquarterly.org/AQ-efecto-naim-report-on-anti-americanism-latin-america)

    * [*Americas Quarterly* 7(2): 45-51.](http://www.americasquarterly.org/gringo-stay-here) [[Version en español]](http://www.americasquarterly.org/gringo-quedate-aqui)

    * [*El Tiempo*](http://www.eltiempo.com/archivo/documento/CMS-12904202)

    * [*Americas Society: Council of the Americas*](http://www.as-coa.org/watchlisten/video-latin-america-goes-global-americas-quarterly-spring-2013-launch-part-ii) [[Video]](https://www.youtube.com/watch?v=Mcd-zsSTdjs)

    * [*La Vuelta*](https://soundcloud.com/lavueltablog/la-vuelta-episode-one) [[Podcast interview]](https://soundcloud.com/lavueltablog/la-vuelta-episode-one)

    * [Understanding Latin American Politics](https://clas-pages.uncc.edu/gregory-weeks/2017/02/03/episode-21-anti-americanism-in-latin-america/) [[Podcast inteview of Cupery]](https://clas-pages.uncc.edu/gregory-weeks/2017/02/03/episode-21-anti-americanism-in-latin-america/)

* Andy Baker and Kenneth F. Greene (2011). ["The Latin American Left's Mandate: Free Market Policies and Issue Voting in New Democracies."](https://www.cambridge.org/core/journals/world-politics/article/abs/latin-american-lefts-mandate-freemarket-policies-and-issue-voting-in-new-democracies/694ED5A111E4E02290387D3DC44173C2) *World Politics* 63(1): 43-77. [Online appendix.](./Latin American Left's Mandate ON-LINE APPENDIX.pdf) [Data.](https://www.dropbox.com/s/1clfjc2g4pc6tis/VRL%20Website%20Data.zip?dl=0)

* Chappell Lawson, Gabriel S. Lenz, Andy Baker, Michael Myers (2010). ["Looking Like a Winner: Candidate Appearance and Electoral Success in New Democracies."](https://www.jstor.org/stable/40891390) *World Politics* 62(4): 561-93.

 * Mentioned in the following mass media outlets:
    * My Science, July 27, 2010.
    
    * [National Affairs, October 8, 2010.](http://www.nationalaffairs.com/blog/detail/findings-a-daily-roundup/leadership-and-elections)
    
    * [The New Republic, October 12, 2010.](https://newrepublic.com/article/78335/the-case-against-voters-part-infinity)

    * [New York Magazine, August, 3, 2010.](http://nymag.com/daily/intelligencer/2010/08/will_the_gop_recapture_the_whi.html)

    * [Morning Edition, WBUR, July 29, 2010.](https://shass.mit.edu/multimedia/video-2010-lenz-wbur)

    * [Politico, August 3, 2010.](https://www.politico.com/story/2010/08/appearances-matter-in-politics-040590)

    * [Reuters, July 29, 2010.](https://in.reuters.com/article/idINIndia-50470120100728)

    * [Wall Street Journal: Week in Ideas, October 16, 2010.](https://www.wsj.com/articles/SB10001424052748703673604575550071622397954)

* Barry Ames, Andy Baker, Lucio R. Renno (2009). ["Split-Ticket Voting as the Rule: Voters and Permanent Divided Government in Brazil."](https://www.sciencedirect.com/science/article/abs/pii/S0261379408000875) *Electoral Studies* 28:8-20.

* Andy Baker and Ethan Scheiner (2007). ["Electoral System Effects and Ruling Party Dominance in Japan: A Counterfactual Simulation Based on Adaptive Parties."](https://www.sciencedirect.com/science/article/abs/pii/S0261379407000224) *Electoral Studies* 26: 447-91.

* Andy Baker, Barry Ames, and Lucio R. Renno (2006). ["Social Context and Campaign Volatility in New Democracies: Networks and Neighborhoods in Brazil's 2002 Elections."](https://www.jstor.org/stable/3694279) *American Journal of Political Science* 50(2): 382-99.

* Andy Baker (2005). ["Who Wants to Globalize? Consumer Tastes and Labor Markets in a Theory of Trade Policy Beliefs."](https://www.jstor.org/stable/3647706) *American Journal of Political Science* 49(4): 924-38.

* Andy Baker and Corey Cook (2005). ["Representing Black Interests and Promoting Black Culture: The Importance of African American Descriptive Representation in the U.S. House."](https://www.cambridge.org/core/journals/du-bois-review-social-science-research-on-race/article/representing-black-interests-and-promoting-black-culture-the-importance-of-african-american-descriptive-representation-in-the-us-house/12FCDFD9938D3AE43F1F2C21BB58CC63) *DuBois Review* 2(2): 227-46.

* Andy Baker and Ethan Scheiner (2004). ["Adaptive Parties: Party Strategic Capacity under Japanese SNTV."](https://www.colorado.edu/faculty/baker/node/62/attachment) *Electoral Studies* 23(2): 251-78.

* Andy Baker (2003). ["Why is Trade Reform so Popular in Latin America? A Consumption-Based Theory of Trade Policy Preferences."](https://www.sciencedirect.com/science/article/abs/pii/S0261379403000398) *World Politics* 55(3): 423-55.

  * Reprinted in Edward D. Mansfield, ed. (2015). [International Trade and the New Global Economy.](https://www.amazon.com/International-Economy-Horizons-Leadership-Studies/dp/1784712590/ref=sr_1_1?ie=UTF8&qid=1440098584&sr=8-1&keywords=international+trade+and+the+new+global+economy+mansfield) Northampton, MA: Edward Elgar Publishing.

* Lila Rosenthal, Deborah P. Scott, Zeman Kelleta, Astatkie Zikarge, Matthew Momoh, Judith Lahai-Momoh, Michael W. Ross, and Andy Baker (2003). ["Assessing the HIV/AIDS Health Services of African Immigrants to Houston."](https://pubmed.ncbi.nlm.nih.gov/14711169/) *AIDS Education and Prevention* 15(6): 570-580.

* Andy Baker (2002). ["Reformas liberalizantes e aprovação presidencial: a politização dos debates da política econômica no Brasil."](https://www.scielo.br/j/dados/a/XrJDXC6wRSHcxKQbHQwJPng/?lang=pt) *Dados* 45(1): 77-98. ["Free-Market Reform and Presidential Approval: The Politicization of Economic Policy Debates in Brazil." [English version].](https://www.researchgate.net/publication/242115380_FreeMarket_Reform_and_Presidential_Approval_The_Politicization_of_Economic_Policy_Debates_in_Brazil)

* Andrew B. Baker (1997). ["Identifying Political Subcultures in Mexico."](https://ojs.library.okstate.edu/osu/index.php/osub/article/view/8979) *Operant Subjectivity* 20(3/4): 73-96.

----

<h2 id="chapters">Chapters in Edited Volumes</h2>

* Andy Baker and Dalton Dorr (2019). [“Mass Partisanship in Three Latin American Democracies.”](./Baker and Dorr Website.pdf) In Noam Lupu, Virginia Oliveros, and Luis Schiumerini (eds.), C*ampaigns and Voters in Developing Democracies: Argentina in Comparative Perspective.* Ann Arbor, MI: University of Michigan Press, pp. 89-113. [[Purchase the Volume](https://www.amazon.com/Campaigns-Voters-Developing-Democracies-Comparative/dp/0472131281/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=1551368576&sr=8-2-fkmrnull)].

* Barry Ames, Andy Baker, and Amy Erica Smith (2018). [“Social Networks in the Brazilian Electorate.”](https://academic.oup.com/edited-volume/35479/chapter-abstract/303904703?redirectedFrom=fulltext) In Jennifer Nicoll Victor, Alexander H. Montgomery, and Mark Lubell (eds.), *The Oxford Handbook of Political Networks.* New York: Oxford University Press, pp. 855-874. [Published version (gated).](http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190228217.001.0001/oxfordhb-9780190228217) [[Purchase the Volume](https://www.amazon.com/Oxford-Handbook-Political-Networks-Handbooks/dp/0190228210)].

* Andy Baker and Kenneth F. Greene (2015). [“Positional Issue Voting in Latin America.”](./Baker and Greene LAV website.pdf) In Ryan Carlin, Matthew Singer, and Elizabeth Zechmeister (eds.), *The Latin American Voter.* Ann Arbor, MI: University of Michigan Press, pp. 173-194. [[Purchase the Volume](Purchase the Volume)].

* Andy Baker (2015). ["Public Mood and Presidential Election Outcomes in Mexico."](./Mexico 2012 paper Baker website.pdf) In Jorge I. Domínguez, Kenneth F. Greene, Chappell Lawson, and Alejandro Moreno (eds.), *Mexico's Evolving Democracy: A Comparative Study of the 2012 Elections.* Baltimore: Johns Hopkins University Press. [[Purchase the Volume](https://www.amazon.com/Mexicos-Evolving-Democracy-Comparative-Elections/dp/1421415542/ref=sr_1_1?ie=UTF8&qid=1417730436&sr=8-1&keywords=mexico%27s+evolving+democracy)].

* Andy Baker (2010). ["La Viabilidad Política y la Popularidad Masiva de los TLC."](https://www.wilsoncenter.org/sites/default/files/media/documents/publication/Peru_US.pdf) In José Raúl Perales y Eduardo Moron, eds., *La Economía Política del Tratado de Libre Comercio entre Perú y Estados Unidos.* Washington, D.C.: Woodrow Wilson International Center for Scholars, pp. 43-50. ["The Political Viability and Mass Popularity of Free Trade in Latin America." [English version].](./Baker in Perales English.pdf)

* Andy Baker (2009). ["Regionalized Voting Behavior and Political Discussion in Mexico."](https://www.researchgate.net/publication/310912014_Regionalized_voting_behavior_and_political_discussion_in_Mexico) In Jorge I. Domínguez, Chappell Lawson, and Alejandro Moreno, eds., *Consolidating Mexico's Democracy: The 2006 Presidential Campaign in Comparative Perspective.* Baltimore: Johns Hopkins University Press, pp. 71-88. [[Purchase the Volume](https://www.amazon.com/Consolidating-Mexicos-Democracy-Presidential-Comparative/dp/080189252X/ref=sr_1_1?ie=UTF8&s=books&qid=1258492761&sr=8-1)]. [[On-line Appendix](./Chapter 4 - On-Line Appendix.pdf)].

* Barry Ames, Andy Baker, and Lucio R. Renno (2008). ["The 'Quality' of Elections in Brazil: Policy, Performance, Pageantry, or Pork?"](https://www.researchgate.net/publication/286282296_The_Quality_of_Elections_in_Brazil_Policy_Performance_Pageantry_or_Pork) In Timothy J. Power and Peter R. Kingstone, eds., *Democratic Brazil Revisited.* Pittsburgh: University of Pittsburgh Press. [[Buy it here](https://www.amazon.com/Democratic-Brazil-Revisited-American-Studies/dp/0822960044/ref=sr_1_4?ie=UTF8&s=books&qid=1219331346&sr=1-4)].

----

<h2 id="other_publications">Other Publications</h2>

* Andy Baker, Sarah Berens, Germán Feierherd, and Irene Menéndez González (2020). [“Labor Informality and its Political Consequences in Latin America.”](https://www.vanderbilt.edu/lapop/insights/IO944es.pdf) *LAPOP Insights Series*, #144. Spanish version: [“Informalidad laboral y sus consecuencias políticas en América Latina.”](https://www.vanderbilt.edu/lapop/insights/IO944es.pdf) 

* Andy Baker (2019). [“Review of J.P. Singh. Sweet Talk: Paternalism and Collective Action in North–South Trade Relations.”](https://doi.org/10.1017/S1537592719000938) *Perspectives on Politics* 17(2): 628-629.

* Andy Baker (2018). [“Review of Richard Nadeau, Éric Bélanger, Michael S. Lewis-Beck, Mathieu Turgeon, and François Gélineau. Latin American Elections: Choice and Change.”](https://doi.org/10.1017/lap.2018.11) *Latin American Politics and Society* 60(2): 118-121.

* Andy Baker, Carew Boulding, Shawnna Mullenax, Galen Murton, Meagan Todd, Ximena Velasco-Guachalla, and Drew Zackary (2017). [“Maintaining Civic Space in Backsliding Regimes.”](https://www.usaid.gov/sites/default/files/2022-05/Maintaining_Civic_Space_in_Backsliding_Regimes_-_Research_and_Innovation_Grants_Working_Papers_Series.pdf) *Research and Innovation Grants Working Papers Series.* Washington, D.C.: USAID and IIE. [Project website.](https://www.iie.org/Research-and-Insights/Publications/DFG-CU-Publication)

* Andy Baker (2015). ["White Americans are Supportive of Redistribution to Foreigners of African Descent, but for Prejudicial and Paternalistic Reasons."](http://blogs.lse.ac.uk/usappblog/2015/03/13/white-americans-are-supportive-of-redistribution-to-foreigners-of-african-descent-but-for-prejudicial-and-paternalistic-reasons/) *USAPP: The LSE's Daily Blog on American Politics and Policy.* March 13.

* Andy Baker (2015). "[Media Portrayals of Africa Promote Paternalism."](https://www.washingtonpost.com/news/monkey-cage/wp/2015/03/05/media-portrayals-of-africa-promote-paternalism/?utm_term=.74910a05eb51) *Monkey Cage: Washington Post.* March 5.

* Andy Baker (2014). ["Latin Americans are Embracing Globalization and their Former Colonial Masters."](https://www.washingtonpost.com/news/monkey-cage/wp/2014/06/02/latin-americans-are-embracing-globalization-and-their-former-colonial-masters/?utm_term=.9d025041aa48) *Monkey Cage: Washington Post.* June 2.

* Andy Baker and David Cupery (2013). ["Gringo Stay Here!"](http://americasquarterly.org/gringo-stay-here) *Americas Quarterly* 7(2): 45-51. [[Version en español](http://www.americasquarterly.org/gringo-quedate-aqui)].

* Andy Baker (2010). "Review of Jude Hays, Globalization and the New Politics of Embedded Liberalism." *Political Studies Quarterly* 125(4): 717-719.

* Andy Baker (2009). "Review of Larry Diamond, Marc. F. Plattner, and Diego Abente Brun, eds., Latin America's Struggle for Democracy." *Latin American Politics and Society* 51(3):164-167.

* Andy Baker (2006). "Government and Politics: Brazil." *Handbook of Latin American Studies*, No. 61. 61: 425-38.

* Andy Baker (2004). "Review of Kurt Weyland, The Politics of Market Reform in Fragile Democracies: Argentina, Brazil, Peru, and, Venezuela." *Journal of Politics* 66(2): 643-45.

* Andy Baker (2002). "Marketing Spectator Sports with Violence: The National Football League." *GSC Quarterly* 4(Spring).

* Andy Baker (2001). "Review of Peter R. Kingstone and Timothy J. Power, eds., Democratic Brazil: Actors, Institutions and Processes." *Luso-Brazilian Review* 38(1): 130-31.
