---
title: Data
---

#### [Measurement-of-Partisanship Experiments in Three Countries: Brazil 2014, Mexico 2016, and Russia 2015.](https://doi.org/10.7910/DVN/HK213D)

<p style="text-align: justify;">Survey question wording experiments on party ID. Three nationwide surveys. Brazil experiment was part of Brazilian Electoral Panel Study (BEPS) 2014 (N=3,120). Mexico experiments were part of Data Opinión Pública y Mercados Omnibus Survey, February 2016 (N=1,208). Russia experiments were part of Levada Centre's Omnibus Survey, November 2015 (N=1,602).</p>

Used in:
<ul style="margin-top: 0;">
<li> Andy Baker and Lucio Renno (2019). [“Nonpartisans as False Negatives: The Mismeasurement of Party Identification in Public Opinion Surveys.”](https://www.colorado.edu/faculty/baker/node/117/attachment) *Journal of Politics*.
</ul>

----

#### [Race, Paternalism, and Foreign Aid: Two Population-Based Survey Experiments of U.S. Respondents (2011 and 2012).](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0FXKKX)

<p style="text-align: justify;">Two nationwide surveys conducted over the internet with embedded experiments and about a dozen post-treatment measures of foreign aid attitudes, paternalism, and resentment. Datasets also contain demographic data. The CM experiment was carried out by Knowledge Networks and funded by TESS (N=2,031, white respondents only). The AG experiment was carried out by the Cooperative Congressional Elections Study (N=1,000). File also contains R code.</p>

Used in:
<ul style="margin-top: 0;">
<li> Andy Baker (2015). ["Race, Paternalism, and Foreign Aid: Evidence from U.S. Public Opinion."](https://www.colorado.edu/faculty/baker/node/32/attachment) American Political Science Review 109(1): 93-109.
</ul>

----

#### [Latin American Election Results with Party Ideology Scores. 2.0 (1993 to present).](https://www.dropbox.com/sh/lu5pteaoqynx15j/AACOuOvmcvDuigqaHp5W1ThLa?dl=0)

<p style="text-align: justify;">Election results and party ideology scores for all Latin American presidential and lower house elections. Used to calculate Vote-Revealed Leftism (VRL), a measure of an electorate's ideological slant as expressed through its voting behavior. This dataset is used (among other things) to estimate how well the left and right have performed in recent Latin American elections. We occasionally update the results, and you can view those [here.](https://www.colorado.edu/faculty/baker/latin-american-elections-and-ideology)</p>

<p style="text-align: justify;">**Please note: In July 2016, we released the 2.0 version of the presidential elections dataset, which contains better source documentation and corrects a few small errors in the post-2008 data. Although the differences are minor, you should replace the old version with this 2.0 version if you downloaded it prior to July 2016. Because of the proliferation of many new parties for which we do not yet have expert-generated ideological scores, we are not sure when we will update the legislative elections data.**</p>

Used in:
<ul style="margin-top: 0;">
<li> Andy Baker and Kenneth F. Greene (2011). ["The Latin American Left's Mandate: Free-Market Policies and Issue Voting in New Democracies."](https://www.colorado.edu/faculty/baker/node/44/attachment) World Politics 63(1): 43-77.
</ul>

----

#### [Four-City Brazil Survey (1999 and 2005).](https://doi.org/10.7910/DVN/WHTNTM)

<p style="text-align: justify;">Sample: Representative samples of Belem, Porto Alege, Sao Paulo, and Recife. Topic areas: Market reforms (pension reform, privatization, FDI, free trade), economic assessments, partisanship, ideology, presidential approval, vote choice, media attention, sector of employment, political knowledge. Sample size: N=800 in 1999. N=1000 in 2005.</p>

Used in:
<ul style="margin-top: 0;">
<li> Andy Baker (2009). [*The Market and the Masses in Latin America: Policy Reform and Consumption in Liberalizing Economies.*](https://www.amazon.com/Market-Masses-Latin-America-Liberalizing/dp/0521156238/ref=tmm_pap_title_0?_encoding=UTF8&sr=8-1&qid=1417639743) (Cambridge Studies in Comparative Politics). New York: Cambridge University Press.
<li> Andy Baker (2003). [*"Why is Trade Reform so Popular in Latin America? A Consumption-Based Theory of Trade Policy Preferences."*](https://www.colorado.edu/faculty/baker/node/64/attachment)World Politics 55(3): 423-55.
</ul>

----

#### [Two-City, Six-Wave Panel Survey, Brazil (2002, 2004, 2006).](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XSCFX5)

<p style="text-align: justify;">(Co-PI with Barry Ames and Lucio R. Renno. National Science Foundation Grant, SES #0137088). Sample: Representative samples of (1) Caxias do Sul, Rio Grande do Sul and (2) Juiz de Fora, Minas Gerais. Topic areas: Neighborhood quality of life, worst problems, economic assessments, political participation, media and campaign attention, civil society and neighborhood involvement, political discussion frequency, trust in government and institutions, vote choice, core values, interpersonal persuasion, feeling thermometers of groups and politicians, party identification, ideology, candidate trait assessments, candidate ideological and issues placement, issues self-placement, evaluation of Lula's government, political knowledge, discussant name generator. Sample size: About 25,000 interviews. Special features: Interviews with named political discussants, 100 interviews per neighborhood, six panel waves of interviews and re-interviews.</p>

Used in:
<ul style="margin-top: 0;">
<li> Andy Baker, Barry Ames, and Lucio Renno (2020). [Persuasive Peers: Social Communication and Voting in Latin America.](https://press.princeton.edu/books/paperback/9780691205779/persuasive-peers) (*Princeton Studies in Global and Comparative Sociology*). Princeton, N.J.: Princeton University Press.
<li> Barry Ames, Andy Baker, and Amy Erica Smith (2018). [“Social Networks in the Brazilian Electorate.”](https://www.colorado.edu/faculty/baker/node/92/attachment) In Jennifer Nicoll Victor, Alexander H. Montgomery, and Mark Lubell (eds.), *The Oxford Handbook of Political Networks.* New York: Oxford University Press, pp. 855-874. [Published version (gated).](http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780190228217.001.0001/oxfordhb-9780190228217)
<li> Andy Baker, Barry Ames, Anand E. Sokhey, and Lucio R. Renno (2016). ["The Dynamics of Partisan Identification when Party Brands Change: The Case of the Workers Party in Brazil."](https://www.colorado.edu/faculty/baker/node/28/attachment) *Journal of Politics* 78(1): 197-213.
<li> Anand E. Sokhey, Andy Baker, and Paul Djupe (2015). ["The Dynamics of Socially Supplied Information: Examining Discussion Network Stability over Time."](https://www.colorado.edu/faculty/baker/node/106/attachment) *International Journal of Public Opinion Research* 27(4): 565-587. [Published version (gated)](https://academic.oup.com/ijpor/article/27/4/565/2357405).
<li> Barry Ames, Andy Baker, Lucio R. Renno (2008). ["Split-Ticket Voting as the Rule: Voters and Permanent Divided Government in Brazil."](https://www.colorado.edu/faculty/baker/node/50/attachment) *Electoral Studies* 28:8-20.
<li> Barry Ames, Andy Baker, and Lucio R. Renno (2008). ["The 'Quality' of Elections in Brazil: Policy, Performance, Pageantry, or Pork?"](https://www.colorado.edu/faculty/baker/node/84/attachment) In Timothy J. Power and Peter R. Kingstone (eds.), *Democratic Brazil Revisited.* Pittsburgh: University of Pittsburgh Press.
<li> Andy Baker, Barry Ames, and Lucio R. Renno (2006). ["Social Context and Campaign Volatility in New Democracies: Networks and Neighborhoods in Brazil's 2002 Elections."](https://www.colorado.edu/faculty/baker/node/56/attachment) *American Journal of Political Science* 50(2): 382-99.
</ul>

----

#### [The Mexico 2006 Panel Study.](http://mexicopanelstudy.mit.edu/)

<p style="text-align: justify;">(Senior project member with Chappell Lawson (PI), Kathleen Bruhn, Roderic Ai Camp, Wayne Cornelius, Jorge Domínguez, Kenneth Greene, Joeseph L Klesner, Beatriz Magaloni, James A McCann, Alejandro Moreno, Alejandro Poiré, and David Shirk. National Science Foundation Grant, SES#0517971). Sample: Representative sample of Mexico. Sample size: About 7,000 interviews and re-interviews.</p>

Used in:
<ul style="margin-top: 0;">
<li> Andy Baker, Barry Ames, and Lucio Renno (2020). [Persuasive Peers: Social Communication and Voting in Latin America.](https://press.princeton.edu/books/paperback/9780691205779/persuasive-peers) (*Princeton Studies in Global and Comparative Sociology*). Princeton, N.J.: Princeton University Press.
<li> Joby Schaffer and Andy Baker (2015). ["Clientelism as Persuasion-Buying: Evidence from Latin America."](https://www.colorado.edu/faculty/baker/node/36/attachment) *Comparative Political Studies* 48(9): 1093-1126. [Published version (gated)](http://journals.sagepub.com/doi/abs/10.1177/0010414015574881).
<li> Andy Baker and Kenneth F. Greene (2015). [“Positional Issue Voting in Latin America.”](https://www.colorado.edu/faculty/baker/node/72/attachment) In Ryan Carlin, Matthew Singer, and Elizabeth Zechmeister (eds.), *The Latin American Voter*. Ann Arbor, MI: University of Michigan Press, pp. 173-194.
<li> Anand E. Sokhey, Andy Baker, and Paul Djupe (2015). ["The Dynamics of Socially Supplied Information: Examining Discussion Network Stability over Time."](https://www.colorado.edu/faculty/baker/node/106/attachment) *International Journal of Public Opinion Research* 27(4): 565-587. Published version (gated).
<li> Andy Baker (2009). ["Regionalized Voting Behavior and Political Discussion in Mexico."](https://www.colorado.edu/faculty/baker/content/baker-ch4-regionalized-voting-behavior) In Jorge I. Domínguez, Chappell Lawson, and Alejandro Moreno (eds.), *Consolidating Mexico's Democracy: The 2006 Presidential Campaign in Comparative Perspective.* Baltimore: Johns Hopkins University Press, pp 71-88.
</ul>